"""Tests for goal origin system (Change #4).

Verifies:
- Auto-generated goals are ENDOGENOUS
- Default goal origin is ENDOGENOUS
- EXOGENOUS goals are not auto-abandoned
- Serialization roundtrip preserves origin
"""

import json
import tempfile
from pathlib import Path

from mimir.brain.belief_graph import BeliefGraph
from mimir.brain.sec_matrix import SECMatrix
from mimir.brain.goal_generator import GoalGenerator
from mimir.types import Belief, BeliefSource, Goal, GoalOrigin, GoalStatus, SECEntry
from mimir.config import MimirConfig
from mimir.state import MimirState
from mimir.brain.memory import Memory


def make_config() -> MimirConfig:
    return MimirConfig(
        goal_pe_threshold=0.3,
        goal_pe_persistence=3,
        goal_staleness_threshold=10,
        max_active_goals=5,
    )


def test_default_goal_origin_is_endogenous():
    """New Goal without explicit origin should be ENDOGENOUS."""
    g = Goal(
        id="g1", target_belief_id="b1",
        description="test", reason="test",
    )
    assert g.origin == GoalOrigin.ENDOGENOUS


def test_auto_generated_investigate_goal_is_endogenous():
    """Goals generated by GoalGenerator from high PE should be ENDOGENOUS."""
    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    gg = GoalGenerator(config, bg, sec)

    b = Belief(
        id="b1", statement="test belief",
        confidence=0.7, source=BeliefSource.OBSERVATION,
        created_at=0, last_updated=5, last_verified=5,
        pe_history=[0.5, 0.4, 0.6, 0.5],
        tags=["test"],
    )
    bg.add_belief(b)

    goals = gg.generate_goals(current_cycle=6)
    assert len(goals) == 1
    assert goals[0].origin == GoalOrigin.ENDOGENOUS


def test_auto_generated_refresh_goal_is_endogenous():
    """Refresh goals should also be ENDOGENOUS."""
    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    gg = GoalGenerator(config, bg, sec)

    b = Belief(
        id="b1", statement="stale belief",
        confidence=0.9, source=BeliefSource.SEED,
        created_at=0, last_updated=0, last_verified=0,
        tags=["stale"],
    )
    bg.add_belief(b)

    goals = gg.generate_goals(current_cycle=15)
    assert len(goals) == 1
    assert goals[0].origin == GoalOrigin.ENDOGENOUS


def test_exogenous_goal_creation():
    """Explicitly creating an EXOGENOUS goal."""
    g = Goal(
        id="g1", target_belief_id="b1",
        description="User goal", reason="User requested",
        origin=GoalOrigin.EXOGENOUS,
    )
    assert g.origin == GoalOrigin.EXOGENOUS


def test_serialization_roundtrip_preserves_origin():
    """Save/load state should preserve goal origin."""
    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    mem = Memory(config)

    goals = {
        "g1": Goal(
            id="g1", target_belief_id="b1",
            description="auto goal", reason="high PE",
            origin=GoalOrigin.ENDOGENOUS,
            created_at=1, priority=0.5,
        ),
        "g2": Goal(
            id="g2", target_belief_id="b2",
            description="user goal", reason="User requested",
            origin=GoalOrigin.EXOGENOUS,
            created_at=2, priority=0.8,
        ),
    }

    with tempfile.TemporaryDirectory() as tmpdir:
        state_path = str(Path(tmpdir) / "state.json")
        MimirState.save(state_path, bg, sec, mem, goals, 5, {})

        _, _, _, loaded_goals, _, _ = MimirState.load(state_path, config)

    assert loaded_goals["g1"].origin == GoalOrigin.ENDOGENOUS
    assert loaded_goals["g2"].origin == GoalOrigin.EXOGENOUS


def test_backward_compat_missing_origin_defaults_endogenous():
    """Old state without origin field should default to ENDOGENOUS."""
    config = make_config()
    data = {
        "cycle_count": 5,
        "belief_graph": {"nodes": {}, "edges": [], "counter": 0},
        "sec_matrix": {"entries": {}},
        "memory": {"episodes": [], "procedures": {}},
        "goals": {
            "g1": {
                "id": "g1",
                "target_belief_id": "b1",
                "description": "old goal",
                "reason": "test",
                "status": "active",
                "created_at": 1,
                "priority": 0.5,
                # No "origin" key
            }
        },
        "usage_stats": {},
    }

    _, _, _, goals, _, _ = MimirState.load_from_dict(data, config)
    assert goals["g1"].origin == GoalOrigin.ENDOGENOUS


def test_preference_belief_does_not_trigger_goal():
    """PREFERENCE category beliefs with high PE should NOT trigger investigate goals."""
    from mimir.types import BeliefCategory

    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    gg = GoalGenerator(config, bg, sec)

    # PREFERENCE belief with high PE
    b = Belief(
        id="b1", statement="I prefer dark mode",
        confidence=0.7, source=BeliefSource.OBSERVATION,
        created_at=0, last_updated=5, last_verified=5,
        pe_history=[0.5, 0.5, 0.5],
        tags=["ui_preference"],
        category=BeliefCategory.PREFERENCE,
    )
    bg.add_belief(b)

    goals = gg.generate_goals(current_cycle=6)
    # Should NOT generate goal for PREFERENCE belief
    investigate_goals = [g for g in goals if "Investigate" in g.description]
    assert len(investigate_goals) == 0


def test_fact_belief_triggers_goal():
    """FACT category beliefs with high PE should trigger investigate goals."""
    from mimir.types import BeliefCategory

    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    gg = GoalGenerator(config, bg, sec)

    b = Belief(
        id="b1", statement="GDP growth is 3%",
        confidence=0.7, source=BeliefSource.OBSERVATION,
        created_at=0, last_updated=5, last_verified=5,
        pe_history=[0.5, 0.5, 0.5],
        tags=["economics"],
        category=BeliefCategory.FACT,
    )
    bg.add_belief(b)

    goals = gg.generate_goals(current_cycle=6)
    assert len(goals) == 1
    assert goals[0].origin == GoalOrigin.ENDOGENOUS


def test_hypothesis_belief_triggers_goal():
    """HYPOTHESIS beliefs with high PE should trigger goals."""
    from mimir.types import BeliefCategory

    config = make_config()
    bg = BeliefGraph(config)
    sec = SECMatrix(config)
    gg = GoalGenerator(config, bg, sec)

    b = Belief(
        id="b1", statement="AI will surpass human intelligence by 2030",
        confidence=0.6, source=BeliefSource.INFERENCE,
        created_at=0, last_updated=5, last_verified=5,
        pe_history=[0.5, 0.5, 0.5],
        tags=["ai_hypothesis"],
        category=BeliefCategory.HYPOTHESIS,
    )
    bg.add_belief(b)

    goals = gg.generate_goals(current_cycle=6)
    assert len(goals) == 1
